// FramePick → FramePick Studio bridge (web side).
//
// The FramePick browser extension delivers handoffs into this app through
// window.postMessage (relayed by its bridge content script). This module
// validates those messages, keeps a small persistent "Inbox" of received
// items, and exposes a subscribe API compatible with useSyncExternalStore.
//
// Contract (single source of truth — the extension mirrors these shapes):
//   { source: 'framepick', type: 'handoff', payload: CompositionHandoff | MotionHandoff }

export interface CompositionHandoff {
	kind: 'composition';
	image: string; // data URL — the picked still, layout/framing reference
	prompt: string; // FLUX.2 still prompt generated by FramePick (the clip as-is)
	heroPrompt?: string; // same prompt with the subject replaced by the @hero token
	sourceUrl?: string;
	ts: number;
}

export interface MotionKeyframe {
	t: number; // seconds
	src: string; // data URL
}

export interface MotionBreakdown {
	shot: string;
	composition: string;
	camera_movement: string;
	scene_action: string;
	evolution: string;
	light_and_grade: string;
}

export interface MotionHandoff {
	kind: 'motion';
	frames: MotionKeyframe[]; // sampled keyframes — motion & layout guides only
	duration: number;
	breakdown: MotionBreakdown;
	videoPrompt: string; // original clip prompt
	heroPrompt: string; // replicated prompt with the subject as the @hero token
	sourceUrl?: string;
	ts: number;
}

export type FramePickHandoff = CompositionHandoff | MotionHandoff;

export interface InboxItem {
	id: string;
	payload: FramePickHandoff;
	receivedAt: number;
}

const INBOX_KEY = 'framepick:inbox:v1';
const INBOX_MAX = 10;

let items: InboxItem[] = loadInbox();
const listeners = new Set<() => void>();

function loadInbox(): InboxItem[] {
	try {
		const raw = JSON.parse(localStorage.getItem(INBOX_KEY) || 'null');
		if (Array.isArray(raw)) return raw.filter((i) => i && i.payload && (i.payload.kind === 'composition' || i.payload.kind === 'motion'));
	} catch {
		/* ignore */
	}
	return [];
}

function persist(): void {
	try {
		localStorage.setItem(INBOX_KEY, JSON.stringify(items));
	} catch {
		// Quota — drop the oldest items and retry once.
		try {
			items = items.slice(0, 4);
			localStorage.setItem(INBOX_KEY, JSON.stringify(items));
		} catch {
			/* non-fatal */
		}
	}
}

function emit(): void {
	listeners.forEach((fn) => fn());
}

export function subscribeInbox(fn: () => void): () => void {
	listeners.add(fn);
	return () => listeners.delete(fn);
}

export function getInbox(): InboxItem[] {
	return items;
}

export function inboxCount(): number {
	return items.length;
}

export function removeInboxItem(id: string): void {
	items = items.filter((i) => i.id !== id);
	persist();
	emit();
}

export function clearInbox(): void {
	items = [];
	persist();
	emit();
}

function isKeyframe(f: unknown): f is MotionKeyframe {
	const o = f as MotionKeyframe;
	return !!o && typeof o.t === 'number' && typeof o.src === 'string' && o.src.startsWith('data:');
}

function validate(payload: unknown): FramePickHandoff | null {
	const p = payload as FramePickHandoff;
	if (!p || typeof p !== 'object') return null;
	if (p.kind === 'composition') {
		if (typeof p.image !== 'string' || !p.image.startsWith('data:')) return null;
		return {
			kind: 'composition',
			image: p.image,
			prompt: String(p.prompt || ''),
			heroPrompt: String(p.heroPrompt || ''),
			sourceUrl: String(p.sourceUrl || ''),
			ts: Number(p.ts) || Date.now(),
		};
	}
	if (p.kind === 'motion') {
		if (!Array.isArray(p.frames) || !p.frames.length || !p.frames.every(isKeyframe)) return null;
		const b = (p.breakdown || {}) as MotionBreakdown;
		return {
			kind: 'motion',
			frames: p.frames.slice(0, 12),
			duration: Number(p.duration) || 0,
			breakdown: {
				shot: String(b.shot || ''),
				composition: String(b.composition || ''),
				camera_movement: String(b.camera_movement || ''),
				scene_action: String(b.scene_action || ''),
				evolution: String(b.evolution || ''),
				light_and_grade: String(b.light_and_grade || ''),
			},
			videoPrompt: String(p.videoPrompt || ''),
			heroPrompt: String(p.heroPrompt || ''),
			sourceUrl: String(p.sourceUrl || ''),
			ts: Number(p.ts) || Date.now(),
		};
	}
	return null;
}

export function addHandoff(payload: FramePickHandoff): void {
	const valid = validate(payload);
	if (!valid) return;
	items = [{ id: `fp-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`, payload: valid, receivedAt: Date.now() }, ...items].slice(0, INBOX_MAX);
	persist();
	emit();
}

// ---------------------------------------------------------------------------
// @hero token resolution — the FramePick motion prompt names its subject with
// the literal token @hero; FramePick Studio resolves it to this shot's Hero slot.
// ---------------------------------------------------------------------------

export const HERO_TOKEN = '@hero';

export function resolveHeroPrompt(prompt: string, opts: { description?: string; hasHeroRef?: boolean }): string {
	const subject = (opts.description || '').trim() || 'the hero subject';
	let out = (prompt || '').split(HERO_TOKEN).join(subject);
	if (opts.hasHeroRef) {
		out += ' The subject is the HERO reference image — preserve its identity, colors, materials and design exactly.';
	}
	return out;
}

// ---------------------------------------------------------------------------
// Window listener — installed once at app start (see main.tsx).
// ---------------------------------------------------------------------------

let installed = false;

function announceReady(): void {
	// tells the extension bridge it is now safe to flush queued handoffs
	window.postMessage({ source: 'framepick-studio', type: 'ready' }, window.location.origin);
}

export function installFramePickListener(): void {
	if (installed || typeof window === 'undefined') return;
	installed = true;
	window.addEventListener('message', (e: MessageEvent) => {
		if (e.source !== window) return;
		const d = e.data as { source?: string; type?: string; payload?: unknown };
		if (!d) return;
		if (d.source === 'framepick' && d.type === 'handoff') addHandoff(d.payload as FramePickHandoff);
		else if (d.source === 'framepick-bridge' && d.type === 'hello') announceReady();
	});
	announceReady();
}
